// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntnqgfrspuafnlctkrfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bnFnZnJzcHVhZm5sY3RrcmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTkxMzUsImV4cCI6MjA2NDUzNTEzNX0.FWoQYCVUu1isxEyDtFPYrpKfSbajPp0G-R73aCJesIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);